### ISSUE TITLE
未发布至 pub.dev

### ISSUE THREAD

**Issue by lijy91** [BuglyDevTeam/Bugly-Flutter-Plugin#2]
现在暂时通过 git repo 引入，希望可以将它发布到 pub.dev 去

```yaml
bugly_crash:
  git:
    url: https://github.com/BuglyDevTeam/Bugly-Flutter-Plugin.git
```
